# publicserver
# tcpproxy
# natserver
# client
Mode = "natserver"
PublicServerAddr = "127.0.0.1:10011"

[TcpProxies]
    [TcpProxies.proxy80]
    LocalBindAddr = "127.0.0.1:1234"
    RemoteServerAddr = "192.168.0.1:80"
    Type = "http"

    [TcpProxies.proxy22]
    LocalBindAddr = "127.0.0.1:1235"
    RemoteServerAddr = "192.168.0.1:22"

[PublicServer]
LocalBindAddr = "0.0.0.0:10011"


[NatServer]
    [NatServer.test]
    RemoteServerAddr = "192.168.0.1:80"
    ID = "test"
    Type = "http"

    [NatServer.test1]
    RemoteServerAddr = "192.168.0.1:22"
    ID = "test1"

[ClientConnect]
    [ClientConnect.test]
    LocalBindAddr = "127.0.0.1:1234"
    ID = "test"

    [ClientConnect.test1]
    LocalBindAddr = "127.0.0.1:1235"
    ID = "test1"
